const content = {
  Predicciones: { eyebrow: 'MOTOR DE PREDICCIÓN', title: 'Predicciones de demanda', intro: 'Anticipa las próximas semanas y convierte señales en decisiones.', cards: [['Demanda esperada', '+18.6%', 'Próximos 30 días'], ['Productos en riesgo', '12', 'Requieren atención'], ['Confianza promedio', '89.2%', 'Modelo actualizado hoy']] },
  'Datos historicos': { eyebrow: 'CENTRO DE DATOS', title: 'Datos históricos', intro: 'Revisa, filtra y prepara la información que alimenta tus modelos.', cards: [['Registros disponibles', '18,429', '6 fuentes conectadas'], ['Última importación', 'Hoy, 08:42', 'Sin errores detectados'], ['Calidad de datos', '96.8%', 'Por encima del objetivo']] },
  Empresas: { eyebrow: 'PORTAFOLIO', title: 'Empresas', intro: 'Gestiona los negocios que forman parte de tu espacio de trabajo.', cards: [['Empresas activas', '3', 'Todas con datos recientes'], ['Sectores cubiertos', '5', 'Alimentos, hogar y más'], ['Crecimiento promedio', '+8.4%', 'Comparado con el mes anterior']] },
  Preferencias: { eyebrow: 'CONFIGURACIÓN', title: 'Preferencias', intro: 'Ajusta el espacio de trabajo y la forma en que recibes información.', cards: [['Alertas activas', '7', 'Notificaciones configuradas'], ['Fuentes conectadas', '6', 'Sincronización automática'], ['Usuarios con acceso', '4', '1 administrador']] },
}

export default function WorkspacePage({ view }) {
  const current = content[view]
  return <div className="page-content workspace-page"><div className="workspace-hero"><div><p className="eyebrow">{current.eyebrow}</p><h1>{current.title}</h1><p className="subtitle">{current.intro}</p></div><button className="refresh-button">{view === 'Preferencias' ? 'Guardar cambios' : 'Crear nuevo'} <span>+</span></button></div><section className="workspace-cards">{current.cards.map(([label, value, note]) => <article className="workspace-card" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section><section className="workspace-table"><div className="table-header"><div><p className="panel-kicker">VISTA DE TRABAJO</p><h2>{view === 'Predicciones' ? 'Oportunidades detectadas' : view === 'Datos historicos' ? 'Fuentes de información' : view === 'Empresas' ? 'Empresas registradas' : 'Configuración del espacio'}</h2></div><button className="outline-button">Filtrar vista</button></div>{['Mercado Norte', 'Casa Raiz', 'Taller 17'].map((item, index) => <div className="workspace-row" key={item}><span className="row-number">0{index + 1}</span><strong>{item}</strong><span>{view === 'Predicciones' ? ['Alta demanda esperada', 'Estacionalidad favorable', 'Crecimiento estable'][index] : view === 'Datos historicos' ? ['Ventas y stock', 'Pedidos y clientes', 'Producción y costes'][index] : view === 'Empresas' ? ['Alimentos y bebidas', 'Hogar y decoracion', 'Manufactura ligera'][index] : ['Alertas y resúmenes', 'Importación automática', 'Permisos de usuarios'][index]}</span><b className={index === 0 ? 'row-status good' : 'row-status'}>{index === 0 ? 'Activo' : 'En revisión'}</b><span className="company-arrow">→</span></div>)}</section></div>
}
