import { useEffect, useMemo, useState } from 'react'
import Icon from '../../components/ui/Icon'
import { inventoryProducts } from '../../data/dashboardData'
import { listarProductos, normalizarProducto } from '../../routes/api'

const categories = ['Todos', 'Enlatados', 'Despensa básica', 'Limpieza', 'Bebidas', 'Snacks', 'Higiene']
const catalogProducts = inventoryProducts.map((product, index) => ({ ...product, displaySku: ['AB-ATU-01', 'AB-ARR-02', 'LP-DET-03', 'AB-ACE-04'][index] || product.sku, displayCategory: ['Enlatados', 'Despensa básica', 'Limpieza', 'Despensa básica'][index] || product.category }))

function PageHeader({ eyebrow, title, description, action }) {
  return <div className="workbench-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{description}</p></div>{action}</div>
}

export function CatalogPage({ query, onQueryChange, onOpenModal }) {
  const [category, setCategory] = useState('Todos')
  const [backendProducts, setBackendProducts] = useState(catalogProducts)
  useEffect(() => { listarProductos(1).then((data) => setBackendProducts(data.map((item, index) => ({ ...normalizarProducto(item, index), displaySku: `PROD-${item.producto_id}`, displayCategory: item.categoria_id ? `Categoria ${item.categoria_id}` : 'Sin categoría' })))).catch(() => {}) }, [])
  const products = useMemo(() => backendProducts.filter((product) => (category === 'Todos' || product.displayCategory === category) && `${product.name} ${product.displaySku}`.toLowerCase().includes(query.toLowerCase())), [backendProducts, category, query])
  return <div className="page-content workbench-page"><PageHeader eyebrow="MAESTRO DE ARTÍCULOS DE ABARROTES" title="Catálogo de Productos" description="Gestiona los productos base para alimentar el modelo de predicción y ventas." action={<button className="primary-button" onClick={() => onOpenModal({ eyebrow: 'Catálogo', title: 'Nuevo producto', children: <p>El formulario de alta de productos estará disponible para conectar el catálogo con tu API CRUD.</p> })}>+ Nuevo Producto</button>} /><section className="catalog-toolbar"><label className="catalog-search"><Icon name="search" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Buscar por producto o SKU..." /></label><span className="toolbar-label">FILTRAR:</span>{categories.map((item) => <button className={category === item ? 'filter-chip active' : 'filter-chip'} key={item} onClick={() => setCategory(item)}>{item}</button>)}</section><section className="catalog-table"><div className="catalog-table-head"><span>SKU / CÓDIGO</span><span>NOMBRE DEL PRODUCTO</span><span>CATEGORÍA</span><span>STOCK ACTUAL</span><span>ACCIONES</span></div>{products.map((product) => <button className="catalog-row" key={product.id} onClick={() => onOpenModal({ eyebrow: product.displaySku, title: product.name, children: <div><p>{product.reason}</p><p><strong>{product.available} piezas</strong> disponibles · demanda de 30 días: <strong>{product.demand30} unidades</strong>.</p></div>, actions: <button className="primary-button" onClick={() => onOpenModal(null)}>Cerrar</button> })}><code>{product.displaySku}</code><span className="catalog-name"><span className={`product-avatar ${product.tone}`}>{product.avatar}</span><span><strong>{product.name}</strong><small>{product.reason}</small></span></span><span className="catalog-category">{product.displayCategory}</span><span className={product.available < product.minimum ? 'stock-low' : ''}>{product.available} piezas</span><span className="catalog-actions">✎ / ▣</span></button>)}{products.length === 0 && <p className="empty-state">No encontramos productos con esa búsqueda.</p>}</section></div>
}

export function RecommendationsPage({ query, onQueryChange, onOpenModal }) {
  const recommendations = catalogProducts.filter((product) => product.risk === 'Critico' || product.risk === 'Bajo')
  const filtered = recommendations.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()))
  return <div className="page-content workbench-page"><PageHeader eyebrow="CÁLCULO CONSOLIDADO" title="Recomendaciones de Compra" description="Productos con requerimiento de reposición sugerido por el modelo predictivo para evitar quiebres de stock." action={<span className="attention-summary"><i />Atención requerida <small>esta semana</small></span>} /><section className="recommendation-kpis"><article><span>REQUERIMIENTO INMEDIATO</span><strong>{filtered.length} <small>productos</small></strong><em>△ {filtered.length} críticos por agotarse</em></article><article><span>VENTANA DE PROYECCIÓN</span><strong>15 / 30 <small>días</small></strong><em>Horizonte analizado dinámico</em></article><article><span>MODO DE CONSULTA</span><strong>100%</strong><em>Vista consolidada de abarrotes</em></article></section><section className="recommendation-tabs"><button className="active">Todos ({filtered.length})</button><button>Solo críticos por agotarse</button><button>Reorden preventivo</button><label className="catalog-search"><Icon name="search" /><input value={query} onChange={(event) => onQueryChange(event.target.value)} placeholder="Buscar por producto o SKU..." /></label></section><div className="recommendation-list">{filtered.map((product) => <article className="recommendation-card" key={product.id}><span className="recommendation-severity">● STOCK POR AGOTARSE</span><span className={`product-avatar ${product.tone}`}>{product.avatar}</span><div className="recommendation-product"><code>{product.sku}</code><h2>{product.name}</h2><p>Stock actual: <strong>{product.available} unidades</strong> · Confianza: <strong>{product.rotation === 'Alta' ? 'Alta' : 'Media'}</strong></p></div><div className="recommendation-buy"><span>CANTIDAD RECOMENDADA</span><strong>Comprar {Math.max(product.demand30 - product.available, 24)} unidades</strong><small>Cubrir demanda pico proyectada</small></div><div className="recommendation-date"><span>FECHA LÍMITE DE ORDEN</span><strong>Antes del {product.breakDate}</strong><small>para evitar quiebre en anaquel</small></div><button className="detail-button" onClick={() => onOpenModal({ eyebrow: product.sku, title: 'Detalle de predicción', children: <p>{product.reason} Recomendación actual: comprar {Math.max(product.demand30 - product.available, 24)} unidades.</p> })}>Ver detalle de predicción <Icon name="arrow" /></button></article>)}</div></div>
}

export function HistoryPage() {
  const [file, setFile] = useState(null)
  const [uploadStatus, setUploadStatus] = useState('')
  const upload = async (selectedFile) => { setFile(selectedFile); if (!selectedFile) return; try { const { importarVentas } = await import('../../routes/api'); const result = await importarVentas(1, selectedFile); setUploadStatus(`${result.filas_procesadas || 0} filas importadas correctamente.`) } catch (error) { setUploadStatus(error.message) } }
  return <div className="page-content workbench-page"><PageHeader eyebrow="HISTORIAL Y MOVIMIENTOS" title="Carga de Historial" description="Ingresa tus registros de venta de abarrotes para alimentar los modelos predictivos y conocer variaciones de stock físico al instante." action={<span className="sync-badge">● Sistema sincronizado</span>} /><section className="history-maturity"><div><span>MADUREZ DEL MODELO DE IA</span><strong>42 <small>días de historial cargados</small></strong></div><div className="history-message">✓ Historial suficiente: tu cuenta ya puede generar predicciones. Carga 48 días adicionales para alcanzar los 90 días recomendados.</div><div className="history-progress"><span /></div><div className="history-targets"><article>◉ <strong>30 días — Mínimo</strong><small>Predicciones de punto de reorden</small></article><article>↗ <strong>90 días — Recomendado</strong><small>Mayor precisión predictiva calculada</small></article></div></section><div className="history-grid"><section className="history-card"><h2>1. Carga de Ventas</h2><p>Actualiza la base estadística con las ventas de tu negocio.</p><div className="upload-zone"><span>⇧</span><strong>{file ? file.name : 'Arrastra y suelta tu archivo aquí'}</strong><small>Archivos permitidos: .xlsx · .csv</small><label className="primary-button">Seleccionar archivo<input type="file" accept=".xlsx,.csv" onChange={(event) => upload(event.target.files?.[0])} /></label>{uploadStatus && <small>{uploadStatus}</small>}</div></section><section className="history-card"><h2>2. Movimiento de Inventario</h2><p>Los movimientos se gestionan en una próxima ruta CRUD del backend.</p><div className="upload-zone"><span>◌</span><strong>Registro pendiente de endpoint</strong><small>El backend actual no expone /movimientos.</small></div></section></div></div>
}

export function SubscriptionPage() {
  return <div className="page-content workbench-page"><PageHeader eyebrow="FACTURACIÓN & CONTROL" title="Configuración de Suscripción" description="Administra tu plan, próximos cargos y servicios incluidos." action={<span className="account-badge">ID Cuenta: #PYME-9842</span>} /><section className="subscription-layout"><article className="subscription-main"><div><span>Suscripción actual</span><h2>Plan PyME <b>● Activo</b></h2></div><strong className="subscription-price">$499 <small>MXN / mes</small></strong><div className="subscription-cards"><article>▣<strong>PRÓXIMA RENOVACIÓN</strong><b>15 de Noviembre de 2024</b><small>Cargo automático programado</small></article><article>▣<strong>MÉTODO REGISTRADO</strong><b>Tarjeta terminada en 4291</b><small>Visa Débito</small></article></div><div className="subscription-actions"><span>◉ Conectado a la infraestructura de cobro cifrada</span><button>Cancelar suscripción</button><button className="primary-button">Actualizar método</button></div></article><aside className="subscription-side"><h2>Alcance Plan PyME Activo</h2><p>✓ Modelos de recomendación diaria</p><p>✓ Alertas de quiebre de stock</p><p>✓ Acceso multiusuario</p><div className="receipt">▣ Último Recibo<br /><small>15 Oct 2024 · $499 MXN</small></div></aside></section></div>
}
